# Generated by Django 2.2.2 on 2019-06-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Roll_Number', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('College', models.CharField(max_length=100)),
                ('passedout_year', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('course_fee', models.IntegerField()),
                ('Institute_area', models.CharField(max_length=100)),
            ],
        ),
    ]
