# Generated by Django 2.2.2 on 2019-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsection', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('s', 'studentsection'), ('a', 'admin')], max_length=3),
        ),
    ]
