# Generated by Django 2.2.2 on 2019-07-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsection', '0007_auto_20190715_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Fieles',
            field=models.FileField(null=True, upload_to='profile/pdfs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/pic/'),
        ),
    ]
