# Generated by Django 2.2.2 on 2019-07-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsection', '0008_auto_20190716_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Fieles',
        ),
    ]
